### ISSUE TITLE
Auto format doesn't respect sublime indentation settings

### ISSUE THREAD

**Issue by strigonLeader** [crystal-lang-tools/sublime-crystal#39]
If my indentation is tabs or different form 2 spaces saving the file with trailing whitespace will cause it to get converted to two spaces.

Issue on ST3 with the following config:

``` json
{
	"color_scheme": "Packages/Colorsublime - Themes/Flatland_Black.tmTheme",
	"detect_indentation": true,
	"draw_white_space": "all",
	"ensure_newline_at_eof_on_save": true,
	"font_size": 10,
	"hot_exit": false,
	"ignored_packages":
	[
		"Emmet"
	],
	"remember_open_files": false,
	"theme": "Adaptive.sublime-theme",
	"trim_trailing_white_space_on_save": true,
	"vintage_start_in_command_mode": true,
	"vintage_use_clipboard": true
}
```

**Comment by waj** [comment]
It’s by design. The formatter encourages everyone to use the same indentation style. It’s actually something that comes with the compiler and not related with this plugin.

**Comment by strigonLeader** [comment]
Ok.

I've disabled auto_format for now. I understand that you want to have a consistent style for the crystal-lang code base and that having the compiler enforce that in some way is one of the best ways to do it but overriding editor settings for it seems wrong.

Thanks for the help.

**Comment by RX14** [comment]
This is really an artifact of two things: the formatter is external to sublime and non-configurable, and sublime plugin enables the formatter by default. If we disable the formatter by default, we respect the sublime settings but the feature is less discoverable to people who choose the formatter. We keep it on by default because most people use the formatter
